### PR TITLE
Guard against className being null/undefined

### PR DESCRIPTION
**Pull request by developit**
We're seeing this line throw when `element.className` is `null`.

### CODE REVIEW

**Comment by ausi** [comment]
Do you have any information about how `element.className` can be `null`? Maybe a link to a website where this happens?

**Comment by developit** [comment]
Can't seem to reproduce it outside the private case I was seeing, but `className` is `undefined` for `Document`, `Text` and `Comment` nodes.  Also for any SVG element, it's actually an Object:

https://jsfiddle.net/developit/gsLnt0cn/

**Comment by ausi** [comment]
How about using this version then:

```js
(element.getAttribute('class') || '').split(/\s+/).forEach(function(className) {
	foundRules = foundRules.concat(rules['.' + className] || []);
});
```

Does this solve your issue?

**Comment by developit** [comment]
Yup! Updated the PR.
I actually managed to catch this exception today and can confirm it's happening on SVG elements (a `<g>` in this case):
screen shot 2017-04-21 at 3 51 03 pm

**Comment by ausi** [comment]
Thank you for the pull request!

I added some tests and more fixes for SVG elements.

**Pull request merged**
